# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Configuratiebestand voor BasieBeats
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
muw_cred: "C:/pws_db/muw_creds.RDS"
log_home: C:/Users/nipper/Logs
